import type { Metadata } from "next";
import { Rubik } from "next/font/google";

import { LayoutClient } from "@/modules/layout-client";

import "./globals.css";
import { ResponsiveBlock } from "./responsive-block";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={[
          rubik.className,
          "flex flex-col items-center justify-center",
          "min-h-screen",
          "sm:p-4",
          "bg-slate-800 text-slate-200",
        ].join(" ")}
      >
        <LayoutClient>{children}</LayoutClient>
        <ResponsiveBlock />
      </body>
    </html>
  );
}
